"""Initial migration: create users table

Revision ID: 3c71d37bfd9b
Revises: 35d30f238bb0
Create Date: 2025-04-21 00:00:26.681266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c71d37bfd9b'
down_revision: Union[str, None] = '35d30f238bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
